export const CONVERT_HISTORY_REQUEST: string = "CONVERT_HISTORY_REQUEST";
export const CONVERT_HISTORY_SUCCESS: string = "CONVERT_HISTORY_SUCCESS";
export const CONVERT_HISTORY_FAIL: string = "CONVERT_HISTORY_FAIL";

export const CREATE_HISTORY_REQUEST: string = "CREATE_HISTORY_REQUEST";
export const CREATE_HISTORY_SUCCESS: string = "CREATE_HISTORY_SUCCESS";
export const CREATE_HISTORY_FAIL: string = "CREATE_HISTORY_FAIL";

export const CURRENCY_LIST_REQUEST: string = "CURRENCY_LIST_REQUEST";
export const CURRENCY_LIST_SUCCESS: string = "CURRENCY_LIST_SUCCESS";
export const CURRENCY_LIST_FAIL: string = "CONVERT_PROCESS_FAIL";
